version: "3.8"
volumes:
  nginx-conf:
  nginx-vhost:
  public-html:
  nginx-certs:
  nginx-tmpl:

networks:
  reverseproxy:
    external: true
    name: reverseproxy
  internal:

services:
  nginx-proxy:
    image: nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - public-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
    networks:
      - reverseproxy
      - internal
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
  nginx-proxy-gen:
    image: helder/docker-gen
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - reverseproxy
    labels:
     - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    volumes:
      - nginx-conf:/etc/nginx/conf.d
#      - nginx-vhost:/etc/nginx/vhost.d
#      - public-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - nginx-tmpl:/etc/docker-gen/templates
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - internal
    environment:
      - DEFAULT_EMAIL=duvalhubbot@gmail.com
    volumes:
#      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - public-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
  test-app:
    image: nginxdemos/hello
    deploy:
      replicas: 4
    environment:
      - VIRTUAL_HOST=hello.testapp.dev.philippeduval.ca
      - LETSENCRYPT_HOST=hello.testapp.dev.philippeduval.ca
    networks:
      - reverseproxy
